name: Continuous Deployment

on:
  push:
    branches:
      - master
      - feature/add-cd # TODO: Temporary

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

#  deploy:
#    name: Deploy to hosted server
#    environment: production
#    runs-on: ubuntu-latest
#    steps:
#      - name: Remote ssh
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{secrets.REMOTE_HOST}}
#          username: ${{secrets.REMOTE_USER}}
#          password: ${{secrets.REMOTE_PASSWORD}}
#          port: ${{secrets.REMOTE_PORT}}
#          script: |
#            # TODO: Create app/ folder
#            # TODO: Go to app/
#            # TODO: Copy docker-compose.yml
#            # TODO: Stop Compose
#            # TODO: Start Compose
